/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChuDaDi: typeof import('./src/components/ChuDaDi.vue')['default']
    ChunLian: typeof import('./src/components/ChunLian.vue')['default']
    CoupletCell: typeof import('./src/components/CoupletCell.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LangSwitch: typeof import('./src/components/LangSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCart: typeof import('./src/components/ShoppingCart.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSpace: typeof import('vant/es')['Space']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTag: typeof import('vant/es')['Tag']
    VanToast: typeof import('vant/es')['Toast']
  }
}
